// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutocompleteController from "./autocomplete_controller";
application.register("autocomplete", AutocompleteController);

import BookmarkButtonController from "./bookmark_button_controller";
application.register("bookmark-button", BookmarkButtonController);

<<<<<<< HEAD
import HeartButtonController from "./heart_button_controller"
application.register("heart-button", HeartButtonController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
import HelloController from "./hello_controller";
application.register("hello", HelloController);
=======
import HeartButtonController from "./heart_button_controller";
application.register("heart-button", HeartButtonController);
>>>>>>> updated delete reviews modal and ratings

import ImagePreviewController from "./image_preview_controller";
application.register("image-preview", ImagePreviewController);

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
