#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running post-merge hooks"
if git diff --name-only HEAD@{1} HEAD | grep --quiet "yarn.lock"
then
  echo "Yarn.lock has changed, updating local dependencies"
  yarn install
fi

if git diff --name-only HEAD@{1} HEAD | grep --quiet "Gemfile.lock"
then
  echo "Gemfile.json has changed, updating local dependencies"
  bundle install
fi

if git diff --name-only HEAD@{1} HEAD | grep --quiet "db/schema.rb" || git diff --name-only HEAD@{1} HEAD | grep --quiet "db/migrate.*"
then
  echo "schema.rb has changed, running migrations"
  rails db:migrate
fi
echo "Finish running post-merge hooks"
